name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  pages: write
  contents: read

# Allow one concurrent deployment
concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CC_DEPLOY_TOKEN }}
          submodules: recursive

      - name: Update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: import assets from submodules
        run: cp -a _posts/assets  _site/

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./_site
          retention-days: 1

  deploy-production:
    if: github.repository == 'Circle-Circuits/circle-circuits.github.io'
    name: Deploy to Github Pages

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        id: download
        with:
          name: dist

      - name: Prepare and validate artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{steps.download.outputs.download-path}}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  deploy-staging:
    if: github.repository == 'Circle-Circuits/_staging'
    name: Deploy to S3
    needs: build
    runs-on: ubuntu-latest

    steps:  
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 900
          role-session-name: GithubActionStaging
          
      - name: Sync files to S3
        run: |
          aws s3 sync --delete . ${{ secrets.S3_BUCKET }}

  keep-alive:
    name: Keep staging alive
    needs: deploy-staging
    runs-on: ubuntu-latest

    steps:
      - name: Wait 90 seconds
        run: sleep 90s

  destroy:
    needs: keep-alive
    uses: ./.github/workflows/destroy.yml
    secrets: inherit
